development:
  adapter: postgresql
  encoding: unicode
  database: ideaspace_development
  pool: 5
  username: kellywaters
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: ideaspace_test
  pool: 5
  username: kellywaters
  password: 